In [6]:
import numpy as np

In [7]:
np.random.seed(0)
X=np.array([   [1,2,3,2.5],
                [2,5,-1,2.0],
                [-1.5,2.7,3.3,-0.8]])

In [8]:
class LayerDense:
    def __init__(self,nInputs,nNeurons):
        self.weights=np.random.randn(nInputs,nNeurons)*0.1
        self.biases=np.zeros((1,nNeurons))
    def forward(self,inputs):
        self.output = inputs@self.weights+self.biases


In [9]:
class ActivationReLU:

    def forward(self, inputs):
        self.output = np.maximum(0, inputs)

In [11]:
l1=LayerDense(4,5)
a1=ActivationReLU()

l1.forward(X)
a1.forward(l1.output)

print(l1.output)
print(a1.output)

[[-0.87480338  0.38839981 -0.12573018 -0.15249159  0.72237094]
 [-1.03333399  0.69668176  0.23234768 -0.85790618  0.74753986]
 [-1.23169487 -0.06278753  0.2734237   0.41693615  1.25366948]]
[[0.         0.38839981 0.         0.         0.72237094]
 [0.         0.69668176 0.23234768 0.         0.74753986]
 [0.         0.         0.2734237  0.41693615 1.25366948]]
