In [1]:
import numpy as np

In [2]:
#3 neurons with 4 inputs gives 3 output values
inputs=[1,2,3,2.5]
weights = [[0.2, 0.8, -0.5, 1],
 [0.5, -0.91, 0.26, -0.5],
 [-0.26, -0.27, 0.17, 0.87]]
biases=[2,3,0.5]

outputs=np.dot(weights,inputs)+biases
print(outputs)

[4.8   1.21  2.385]


In [3]:
# 3 neuurons with 5 batches of 4 inputs gives 5x3 output values

#5x4 input matrix @ 4x3 weight matrix + 1x3bias 
#Gives 5x3 output matrix


In [15]:
# with a batch of n with 4 inputs and 3 neurons we get  nx3 output matrix 
inputs=np.array([   [1,2,3,2.5],
                    [2,5,-1,2.0],
                    [-1.5,2.7,3.3,-0.8]])
weights =np.array( [[0.2, 0.8, -0.5, 1],
                    [0.5, -0.91, 0.26, -0.5],
                    [-0.26, -0.27, 0.17, 0.87]])
biases=[2,3,0.5]
weights2 = np.array([[0.1, -0.14, 0.5],
                    [-0.5, 0.12, -0.33],
                    [-0.44, 0.73, -0.13]])
biases2 = [-1, 2, -0.5]
l1outputs=inputs@weights.T+biases
l2outputs=l1outputs@weights2.T+biases2
# outputs=np.dot(inputs,weights.T)+biases
print(l2outputs)

[[ 0.5031  -1.04185 -2.03875]
 [ 0.2434  -2.7332  -5.7633 ]
 [-0.99314  1.41254 -0.35655]]


In [16]:
# Making a layer object

In [18]:
np.random.seed(0)
X=np.array([   [1,2,3,2.5],
                [2,5,-1,2.0],
                [-1.5,2.7,3.3,-0.8]])

In [21]:
class LayerDense:
    def __init__(self,nInputs,nNeurons):
        self.weights=np.random.randn(nInputs,nNeurons)*0.1
        self.biaes=np.zeros((1,nNeurons))
    def forward(self,inputs):
        return inputs@self.weights+self.biaes

In [23]:
l1=LayerDense(4,5)
l2=LayerDense(5,3)
o1=l1.forward(X)
l2.forward(o1)

array([[-0.04676146, -0.06312478,  0.01743827],
       [-0.06892937, -0.03879458,  0.01626571],
       [-0.03569601, -0.0414762 ,  0.09697637]])