In [92]:
import math
import numpy as np
softmax_output = np.array([0.1, 0.3, 0.6])
traget_output = np.array([0, 0, 1])


loss =  -traget_output @ np.log(softmax_output)
loss

0.5108256237659907

In [133]:
softmax_outputs = np.array([[0.7, 0.1, 0.2],
                            [0.1, 0.5, 0.4],
                            [0.02, 0.9, 0.08]])
class_targets =np.array([0, 1, 1])
class_targets_onehot = np.eye(3)[class_targets]
class_targets_onehot

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.]])

In [134]:
nll = -np.log(softmax_outputs[range(len(class_targets)) ,class_targets])
print(nll)
average_loss = np.mean(nll)
average_loss

[0.35667494 0.69314718 0.10536052]


0.38506088005216804

In [139]:
nll = -(np.log(((softmax_outputs * class_targets_onehot).sum(axis=1))))
print(nll)
average_loss = np.mean(nll)
average_loss

[0.35667494 0.69314718 0.10536052]


0.38506088005216804

In [140]:
# Common loss class
class Loss:
 
    def calculate(self, output, y):
        sample_losses = self.forward(output, y)
        data_loss = np.mean(sample_losses)
        return data_loss

In [146]:
class categorical_cross_entropy_loss(Loss):
    def forward(self, y_pred, y_true):
        y_pred_cliped = np.clip(y_pred, 1e-7, 1 - 1e-7)

        # for category labels

        if len(y_true.shape) == 1:
            correct_confidences = y_pred_cliped[range(len(y_pred)), y_true]

        elif len(y_true.shape) ==2:
            correct_confidences = np.sum(y_pred_cliped * y_true, axis=1)
        
        negative_log_likelihoods = -np.log(correct_confidences)
        return negative_log_likelihoods


In [145]:
loss_function = categorical_cross_entropy_loss()
loss =loss_function.calculate(softmax_outputs, class_targets)
print(loss)
loss =loss_function.calculate(softmax_outputs, class_targets_onehot)
print(loss)

0.38506088005216804
0.38506088005216804


In [142]:
class_targets

array([0, 1, 1])