In [7]:
import numpy as np
import nnfs
from nnfs.datasets import spiral_data
nnfs.init()

In [11]:
class Layer_dense:
    def __init__(self, nInputs, nNeurons):
        self.weights=np.random.randn(nInputs,nNeurons)*0.1
        self.biases=np.zeros((1,nNeurons))
    def forward(self,inputs):
        self.output = inputs@self.weights+self.biases

class Activation_relu:
    def forward(self, inputs):
        self.output = np.maximum(0, inputs)

class Activation_softmax:
    def forward(self, inputs):
        normInouts=inputs-inputs.max(axis=1,keepdims=True)
        self.output=np.exp(inputs)/np.exp(inputs).sum(1,keepdims=True)
class Loss:
    def calculate(self, output, y):
        sample_losses = self.forward(output, y)
        data_loss = np.mean(sample_losses)
        return data_loss
    
class Categorical_cross_entropy_loss(Loss):
    def forward(self, y_pred, y_true):
        samples = len(y_pred)

        y_pred_clipped = np.clip(y_pred, 1e-7, 1 - 1e-7)

        if len(y_true.shape) == 1:
            correct_confidences = y_pred_clipped[range(samples),y_true]   

        elif len(y_true.shape) == 2:
            correct_confidences = np.sum(y_pred_clipped*y_true,axis=1)

        negative_log_likelihoods = -np.log(correct_confidences)
        return negative_log_likelihoods


In [13]:
X, y = spiral_data(samples=100, classes=3)
print(X.shape, y.shape)
dense1  = Layer_dense(2, 3)
activation1 = Activation_relu()
dense2 = Layer_dense(3, 3)
activation2 = Activation_softmax()
loss_function = Categorical_cross_entropy_loss()


(300, 2) (300,)


In [15]:
dense1.forward(X)
activation1.forward(dense1.output)
dense2.forward(activation1.output)
activation2.forward(dense2.output)
print(activation2.output[:5])

[[0.33333334 0.33333334 0.33333334]
 [0.33334634 0.33335543 0.3332982 ]
 [0.33337918 0.33338657 0.33323428]
 [0.33339632 0.33342737 0.33317634]
 [0.3334001  0.3334534  0.3331465 ]]


In [16]:
loss = loss_function.calculate(activation2.output, y)
print(loss)

1.0981911
